FROM node:16

WORKDIR /app

COPY package*.json ./

# Clean install dependencies
RUN npm ci

# This ensures bcrypt is built for the container environment
RUN npm rebuild bcrypt --build-from-source

COPY . .

CMD ["npm", "start"]