version: '3.8'

services:
  frontend:
    build:
      context: ./art-platform
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./art-platform:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./art-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./art-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000